"""empty message

Revision ID: 8de9c683c213
Revises: 
Create Date: 2020-09-05 23:51:27.716748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8de9c683c213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordcount_dev',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('cord19_2020_vecs_word_idx', table_name='cord19_2020_vecs')
    op.drop_table('cord19_2020_vecs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cord19_2020_vecs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vector', postgresql.ARRAY(sa.REAL()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cord19_2020_vecs_pkey')
    )
    op.create_index('cord19_2020_vecs_word_idx', 'cord19_2020_vecs', ['word'], unique=False)
    op.drop_table('wordcount_dev')
    # ### end Alembic commands ###
